//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemporalTablesDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProductsContext : DbContext
    {
        public ProductsContext()
            : base("name=ProductsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }
    
        [DbFunction("ProductsContext", "GetProductsAsOf")]
        public virtual IQueryable<GetProductsAsOf_Result> GetProductsAsOf(Nullable<System.DateTime> pointInTime)
        {
            var pointInTimeParameter = pointInTime.HasValue ?
                new ObjectParameter("pointInTime", pointInTime) :
                new ObjectParameter("pointInTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetProductsAsOf_Result>("[ProductsContext].[GetProductsAsOf](@pointInTime)", pointInTimeParameter);
        }
    }
}
